[build]
  # Build command for React app
  command = "npm run build"
  
  # Directory to publish (React build output)
  publish = "build"
  
  # Base directory (if deploying from subdirectory)
  base = "yieldflow-frontend"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Specify that this is a React app
  REACT_APP_NODE_ENV = "production"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 